name: Sync GitHub Issues

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync issue to another repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          REPO_OWNER="destination-owner"
          REPO_NAME="test-sync"

          curl -X POST -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues \
          -d "{\"title\": \"$ISSUE_TITLE\", \"body\": \"$ISSUE_BODY\"}"
